//LiveCodeNet Ensamble
//crea, coolabora, comparte tus SCtweets
//Contenido html de la ventana principal
"
<textarea id='sctweetArea'></textarea>
<button id='boton'>What The Fuck!!!</button>
 <style type='text/css'>
 #boton {
    background: red;
    position: absolute;
    top: 200px;
    width: 159px;
    height: 38px;
 }
#sctweetArea {
    background: cyan;
    min-height: 200px;
    max-width: 500px;
}
</style>
";